
# ??????
server:
  # ????HTTP??????80
  port: 8083
  servlet:
    # ???????
    context-path: /
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # ?????????????100
    accept-count: 1000
    threads:
      # tomcat?????????200
      max: 800
      # Tomcat?????????????10
      min-spare: 100




# Spring??
spring:
  # ????
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    encoding: utf-8
    # ????
    cache: false











